# Use the PHP 8.3 FPM image
FROM php:8.3-fpm

# Install system dependencies and PHP extensions
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo pdo_mysql

# Set the working directory (this should match the one in docker-compose.yml)
WORKDIR /var/www/

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Command to run the PHP-FPM server
CMD ["php-fpm"]
